consumes:
- application/json
info:
  description: Thyra HTTP server API.
  title: thyra-server
  version: 0.0.0
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
paths:
  /cmd/executeFunction:
    post:
      operationId: cmdExecuteFunction
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - name
              - at
            properties:
              name:
                description: Function name to call.
                type: string
              at:
                description: Smart contract address exporting the function to call.
                type: string
              args:
                description: Arguments to pass to the function.
                type: string
                default: ""
              gaz:
                type: object
                description: Gaz attibutes. Gaz is a virtual resource consumed by node while running smart contract.
                properties:
                  price:
                    type: number
                    description: Price of a gaz unit.
                    default: 0
                  limit:
                    type: integer
                    description: Maximum number of gaz unit that a node will be able consume.
                    default: 700000000
              coins:
                type: object
                description: Coins to be send from caller to smart contract address.
                properties:
                  parallel:
                    description: Number of parallel coins to transfer from the caller to the smart contract address.
                    type: number
                    default: 0
                  sequential:
                    description: Number of sequential coins to transfer from the caller to the smart contract address.
                    type: number
                    default: 0
              expiry:
                description: Set the expiry duration (in number of slots) of the transaction.
                type: integer
                default: 3
              fee:
                description: Set the fee amount (in massa) that will be given to the block creator.
                type: number
                default: 0
              keyId:
                description: Defines the key to used to sign the transaction.
                type: string
                default: ""
      produces:
      - application/json
      responses:
        '200':
          description: OK.
          schema:
            type: string
            description: Operation id.
        '422':
          description: Unprocessable Entity - syntax is correct, but the server was unable to process the contained instructions.
          schema:
            type: object
            description: Error object.
            required:
              - code
              - message
            properties:
              code:
                description: error code.
                type: string
              message:
                description: error message.
                type: string
        '500':
          description: Internal Server Error - The server has encountered a situation it does not know how to handle.
          schema:
            type: object
            description: Error object.
            required:
              - code
              - message
            properties:
              code:
                description: error code.
                type: string
              message:
                description: error message.
                type: string
  /kpi:
    get:
      operationId: kpi
      parameters:
        - name: scope
          in: query
          type: string
          type: array
          minItems: 0
          uniqueItems: true
          collectionFormat: csv
          items:
            type: string
            enum: [wallet, node, stacking, blockchain]
      produces:
      - application/json
      responses:
        '200':
          description: kpi message.
          schema:
            type: object
            properties:
              wallet:
                type: array
                items:
                  type: object
                  properties:
                    coin:
                      type: string
                    balance:
                      type: number
              node:
                type: array
                items:
                  type: object
                  properties:
                    memory:
                      type: array
                      items:
                        type: number
                    cpu:
                      type: array
                      items:
                        type: number
                    storage:
                      type: array
                      items:
                        type: number
                    network:
                      type: array
                      items:
                        type: number
              stacking:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                    rolls:
                      type: integer
                    slashing:
                      type: integer
                    gains:
                      type: number
